[project]
name = "project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Voranto", email = "lucasiegel9@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "cachetools>=7.2.0",
    "fastapi[standard]>=0.141.1",
    "pywavelet>=0.2.10",
    "pywavelets>=1.10.0",
    "structure-tensor>=0.3.4",
]

[project.scripts]
project = "project:main"

[build-system]
requires = ["uv_build>=0.12.15,<0.13.0"]
build-backend = "uv_build"
